### ISSUE TITLE
Text on screens is blending into background color

### ISSUE THREAD

**Issue by rjanicek** [Nine-Minds/alga-psa#16]
Windows 11, latest stable Chrome, dark theme selected for OS and browser.

![image](https://github.com/user-attachments/assets/4d161fa7-ede8-46b5-8d90-89dcb6d4176a)

**Comment by RobertAtNineMinds** [comment]
it looks like dark mode isn't styled correctly yet. You can temporarily work around this by switching dark mode off via the icon in the banner area.

**Comment by NatalliaBukhtsik** [comment]
Fixed-ish, real fix postponed for now.
