### ISSUE TITLE
Can not change Contact or Client on a Ticket

### ISSUE THREAD

**Issue by rjanicek** [Nine-Minds/alga-psa#84]
It is possible to edit but not to select a different Client or Contact on a ticket. We should be able to change contact or client on a ticket in case they were selected in error or contact could change within the company.

![image](https://github.com/user-attachments/assets/7a933ea2-a576-4b46-832f-953056632b86)

**Comment by NatalliaBukhtsik** [comment]
![image](https://github.com/user-attachments/assets/37b588de-9895-479c-8e17-1ac28946180f)
