### ISSUE TITLE
Deployment methods

### ISSUE THREAD

**Issue by travquinn** [Nine-Minds/alga-psa#89]
The current deployment method creates more friction than it needs to and might put alga in the "too hard" basket for many which is likely to hinder adoption.

The current method uses npm, make, and docker - I would suggest that only docker should be required on the host to get a functional configuration up and running. The dockerfile and .env file should do most of the heavy lifting and the entire setup should not require any host dependencies other than docker.

In my opinion, the entire deployment should come down to:
- Pulling the repo
- Running `cp .env.example .env`
- Running `docker compose up -d`

The proposed method is simpler, more efficient, and more platform friendly as most people (particularly non-developers that run Windows) do not have make or NPM on their systems which creates two hurdles for people to jump before they can even start setting up alga. This will allow less technical people and people with only two minutes to spare because their current PSA does no heavy lifting to run alga, which will only foster growth and feedback - building a bigger community and a better PSA!

**Comment by redpimpernel** [comment]
I agree. I would love to try this but the barrier to entry is too high.  Is it possible to have just a compose file?

**Comment by RobertAtNineMinds** [comment]
yeah, I have been concentrating on wrapping up time approvals, and invoicing. Within the next few days, I'll add in a one-liner docker compose command to make it easier to get started.

In the meantime, the video on the project readme should help walk you through what we have now.

**Comment by travquinn** [comment]
Thanks Robert, that's awesome

**Comment by redpimpernel** [comment]
That would be awesome!

**Comment by RobertAtNineMinds** [comment]
I've made some good progress. I'm working on it in this branch:

https://github.com/Nine-Minds/alga-psa/commits/docker-compose-automation/

**Comment by RobertAtNineMinds** [comment]
i have deployed an initial implementation. I am not yet ready to close this as I think there is a still some testing and doc updates left to be done, but the bulk of the work is complete.

**Comment by RobertAtNineMinds** [comment]
Fixed  [https://github.com/Nine-Minds/alga-psa/releases/tag/v0.0.6](v0.0.6)

**Comment by redpimpernel** [comment]
That's great. Thanks!
